untitled1/urls.py
from django.conf.urls import url
from app import views

urlpatterns = [
    url(r'^email/$', views.email, name='email'),
    url(r'^thanks/$', views.thanks, name='thanks'),
    url(r'^', views.main_home, name='main_home'),
]

app/models.py
from django.db import models

# Create your models here.

app/forms.py
from django import forms

class ContactForm(forms.Form):

    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea)

app/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from app.forms import ContactForm
from django.conf import settings
import django

def email(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, from_email+'가 보냄\n\n'+message, from_email, ['roharon@naver.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('thanks')
    return render(request, "email.html", {'form': form})

def thanks(request):
    return HttpResponse('Thank you for your message.')

def main_home(request):
    return render(request, "main.html")

templates/email.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width" initial-scale=3", minimum-scale="3">

    <title>훕스 컴플레인</title>
<style>


input[type=email], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
}
input[type=text], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
}
input[name='message'], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
}
input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

div {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
}

} /* Red */
</style>
</head>

<body>
<div class="form-actions">
<form method="post">

    {% csrf_token %}

    <h2>훕스컴플레인 전달하기</h2>
    <br>
    <p>작성된 내용은 어떠한 수정없이 글로벌캠퍼스 학생회에 바로 전달됩니다.</p>
    <br><br><br>
    <label for="fname">E-Mail</label>
    <input type="text" id="id_from_email" name="from_email" placeholder="이메일을 적으세요" required>
    <label for="fname">제목</label>
    <input type="text" id="id_subject" name="subject" placeholder="제목" required>
    <br>
    <label for="fname">전달할 내용</label>
    <input type="text" id="id_message" name="message" placeholder="전달할 내용" rows="5" required>
    <br>

    <input type="checkbox" id="accpet" required>
    <label for="accpet">이메일 및 작성된 내용 수집에 동의합니다.</label>
    <br>
    <input type="submit" value="전달하기" class="button button3">




</form>
</div>
</body>

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <title>Bootstrap Theme Simply Me</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  .bg-1 {
      background-color: #1abc9c;
      color: #ffffff;
  }
  .bg-2 {
      background-color: #474e5d;
      color: #ffffff;
  }
  .bg-3 {
      background-color: #ffffff;
      color: #555555;
  }
  .container-fluid {
      padding-top: 30px;
      padding-bottom: 60px;
  }
  </style>
</head>

<body>
<div class="code">
<code>
<script type="text/javascript"><!--
function copy_trackback(trb) {
var IE=(document.all)?true:false;
if (IE) {
if(confirm("개발자 이메일을 복사하시겠습니까?"))
window.clipboardData.setData("Text", trb);
} else {
temp = prompt("Ctrl+C를 눌러 클립보드로 복사하세요", trb);
}
}
//--></script>
</code>
</div>

<div class="container-fluid bg-1 text-center">
  <h3>훕스컴플레인</h3>
  <h3>한국외국어대학교 불만사항 제기 사이트</h3>
    <br>
</div>

<div class="container-fluid bg-2 text-center">
    <br>
  <h3>학생회와 교수님에게 메일을 보낼 수 있습니다</h3>
  <br><br>
  <a href="http://hufscomplain.com/email/" class="btn btn-default btn-lg"> 불평하러 가기 </a>
    <br>
    <p>위의 버튼을 눌러주세요</p>
</div>
<footer class="container-fluid bg-4 text-center">
    <br>
    <p>서울캠퍼스도 추가 예정입니다.</p><br>
  <p>개발자 <a href="https://github.com/roharon">GitHub</a>

<a href="roharon@hufs.ac.kr" onclick="copy_trackback(this.href); return false;">이메일
</a>


</footer>


</body>
</html>